# Generated by Django 4.2.6 on 2023-10-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_date_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='text',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
